import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>ProVid</title>
        <meta name="description" content="Generated by Promethewz" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Hello from provid</h1>
      </main>

      <footer className={styles.footer}>Powered by Promethewz</footer>
    </div>
  );
};

export default Home;
